Vagrant.require_version ">= 1.4.3"
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	numNodes = 1
	r = numNodes..1
	(r.last).upto(r.first).each do |i|
		config.vm.define "rnode#{i}" do |node|
			node.vm.box = "centos65"
			node.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"
			node.vm.provider "virtualbox" do |v|
			    v.name = "rnode#{i}"
			    v.customize ["modifyvm", :id, "--memory", "2048"]
			end
			if i < 10
				node.vm.network :private_network, ip: "10.211.51.10#{i}"
			else
				node.vm.network :private_network, ip: "10.211.51.1#{i}"
			end
			node.vm.hostname = "rnode#{i}"
			node.vm.provision "shell", path: "scripts/setup-centos.sh"
			node.vm.provision "shell", path: "scripts/setup-centos-ntp.sh"
			# node.vm.provision "shell", path: "scripts/setup-java.sh"

			node.vm.provision "shell", path: "scripts/setup-R.sh"
			node.vm.provision "shell", path: "scripts/setup-RStudio.sh"
		end
	end
end